name: Test kubectl CMD

on:
  # Is able to be run on-demand (i.e. manually without needing to push code)
  workflow_dispatch:

jobs:
  # Runs a build job only if the lint and test jobs pass and successfully builds the application
  build-job:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    
    steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
  
    - name: Login to Amazon 
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Configure Kubeconfig
      run:
        aws eks update-kubeconfig --name cluster --region us-east-1

    - name: Check current kubectl context
      run:
        kubectl config current-context
        
    - name: Check kubectl version    
      run:
        kubectl version    